### ISSUE TITLE
Update & Add Location Statuses for Carriers

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#108]
Carriers currently have a `Location`, but we need to distinguish between the carrier's home location (where it originated from when added) and which location it is currently assigned to.

- Rename `Location` to `Home Location`. This would be the original location of the item. 
- Add `Current Location` status. This would be a dropdown option in a workflow (not yet implemented) to allow a carrier's `Current Location` to be updated. 

On `/carriers/new`, add this second dropdown for `Current Location` to the page beneath `Location` (which should be renamed to `Home Location`.

![image](https://user-images.githubusercontent.com/47750744/66719224-04666f00-edbb-11e9-9708-7121e8b49169.png)

The basic use case would be:
- Item 1 is purchased/donated for the DelCo location. This is its `Home Location` and would not change on transfer.

- Demand for Item 1 in DelCo (`Home Location`) is low, but there's demand for that item at the ChesCo location. User would be able to select ChesCo as the item's new `Current Location`. 

- Item 1 would then show the following:
- `Home Location` - DelCo
- `Current Location` - ChesCo

**Comment by melissa-hong** [comment]
Hi @abronkema - could I take a stab at this please

The steps as I see it (please correct me if I'm wrong!):
- Rename 'Location' > 'Home Location' in carrier form template (in `Carrier` db table it would still be `location_id`)
- Add `current_location_id` to `Carrier` table
- Add 'Current Location' dropdown to carrier form template (both new carriers and editing existing carriers) and implement saving

**Comment by pollygee** [comment]
HI @melissa-hong thanks so much!
So here's what I was thinking.  We only need one list of locations, because the home and the location could be the same, or maybe they're not......maybe it's on loan to another location for a while?  But they aren't separate places, it's from the same list. I don't know if that makes sense.

So, I was thinking that we could just keep one list in the database as location_id on the carrier, but we could have a relation that a carrier `has_one :location, :as => :home_location` and `has_one :location, :as => :current_location`.  

What do you think about that?

**Comment by melissa-hong** [comment]
Thanks @pollygee - yes that makes sense to me. I've created PR #122 to address this

One issue with my PR that I'm still not sure how to fix - all existing carrier entries will have `current_location_id` set to `nil` however when you edit them, the dropdown will default to the first location value which is misleading. This is the same as for location however it's an issue here because current location is optional. I've tried adding `:include_blank => true` but it doesn't seem to work. Let me know if you have any ideas!

**Comment by cattywampus** [comment]
I wonder if instead of thinking of `current_location` as optional, it's always set with it's original default value in sync with the `home_location`. My thought here would be every carrier has a home location it originally belongs to. In this initial setup it's current location would match it's home location. Once it's transferred to a new location then the current location would be updated. Based on my understanding from above the home location should rarely (if never) change but the current location would like change as the organization moves inventory around. 

If we setup current location to copy the location from home location then it should never be `nil`. 

@pollygee @abronkema Is any of that off the mark?

**Comment by pollygee** [comment]
@melissa-hong awesome thanks so much.  Excited to have you here helping us out.  We are actually a community, so feel free to come join us!  We have a Slack - the invite is on our website www.rubyforgood.org (the # at the top of the page links to the invite) we've got a channel #babywearing where we discuss stuff too, so it's another good place to ask questions and get help.  Here is good too though so no pressure!!

Yeah I like it @cattywampus thanks for chiming it!  `current_location` will probably always start as `current_location` until it's loaned out to another location.  In reality there will be some exceptions to that but they will be few, so we can edit those by hand no problem!   @melissa-hong does this sound do-able?

**Comment by melissa-hong** [comment]
That makes sense @cattywampus, @pollygee - I've updated my PR with a rake task that will set the current location of all existing carriers to the current home location. And since the `/carriers/new` page enforces home/current location selection it should never be nil.
