### ISSUE TITLE
Add rubocop for style consistency

### ISSUE THREAD

**Issue by DamirSvrtan** [rubyforgood/babywearing#182]
Rubocop is the most popular Ruby linter and I'd wanna add the code climate integration so we can hopefully get automatic comments from code climate on style related issues. One of the things we should avoid is focusing on style in PR's specially since it can be done automatically.

I guess code climate can do that for us, if not I know that [Hound](https://houndci.com/) is an option.

I can take on this, just wanna hear if @dixpac, @corprew or anyone else has any other preference. I know there's [standard](https://github.com/testdouble/standard) but that has not hit a stable release yet. Assigning it to myself.

**Comment by dixpac** [comment]
I'm 100% for this. It would be extremely helpful. Used CodeClimate and Hound in the production apps and both will do the job for us. Played with standard but not with the production apps.

One thing I found helpful is adding git hooks that execute rubocop before commit/push.

There are also GithubActions now that we can hook with rubocop but they may be over engineering for this project.

**Comment by pollygee** [comment]
We have plans (when we get time!!!) to get a RubyForGood rubocop so that we can set that up before we start projects and so we have standardization across the apps to make it easier to contribute.  In the meantime, yes, we need to do this individually for projects.  Thanks so much for bringing this up, and for taking this on!
