### ISSUE TITLE
Add a User Link doesn't work

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/babywearing#201]
**Describe the bug**
As an admin, I want to be able to add a user.  When  I click the button I don't get a form to add a user, I get the flash message that I'm already logged in.  Currently one could log out to create a new account.  However, for our users they will have a volunteer or admin logged in checking out carriers etc, and we need them to be able to add users as well.  

**To Reproduce**
1. Go to `/home`
2. Click on `Add a user`

**Expected behavior**
I should get a new page to add another user.

**Comment by sarslanoglu** [comment]
@pollygee I could take a look if it's open for outside contributors

**Comment by pollygee** [comment]
@sarslanoglu that would be awesome!  Thanks so much 👏

**Comment by sarslanoglu** [comment]
These posts are related with my solution to the problem. Fell free to check them.

https://stackoverflow.com/questions/23140117/allow-a-user-to-add-new-users-in-devise-and-remain-logged-in-as-themselves

https://stackoverflow.com/questions/7075873/devise-how-to-create-a-new-user-being-already-logged-in

https://stackoverflow.com/questions/19017978/allowing-admins-to-add-users-with-devise

**Comment by sarslanoglu** [comment]
For future reference: https://github.com/plataformatec/devise/wiki/How-To:-Manage-Users-with-an-Admin-Role-(CanCan-method)

**Comment by pollygee** [comment]
Hi @sarslanoglu just so you know - we are currently using pundit gem not Can-Can.
https://github.com/varvet/pundit

**Comment by sarslanoglu** [comment]
@pollygee My mistake. I didn't use it. Deleted the comment

**Comment by dixpac** [comment]
@pollygee this is not implemented yet `create` is missing here https://github.com/rubyforgood/babywearing/blob/master/app/controllers/users_controller.rb

There are few details that need to be figured out for this:
When admin creates a user, what happens when that user logs in for the first time, should system sent them the link to activate/set password?

**Comment by pollygee** [comment]
I guess this is a feature.  🤷‍♀  I was sure I was creating users before. 
@abronkema do you want to weigh in with workflow?  Maybe we need a different ticket that describes the feature better.

I think when the user is created we want to direct them to the users' agreements so the member can "sign".  The member will create their password when the user is created (they will be on a volunteer's computer but the member will be there doing the signing in).  So they will just get the same regular welcome email as everybody else, but @abronkema is better to speak on that?

**Comment by abronkema** [comment]
@dixpac @pollygee 

I think we need to support two workflows:

1 - Volunteer/Admin signs user up at the meeting location. At account creation, it should immediately direct them to sign the agreements, again, tying the agreement signatures to the new user that's been created. 
- Something like `Create User` > `Edit/Add User Page` > "Create/Confirm" > `Agreement 1 Signature` > `Agreement 2 Signature` > Email Copies and Confirmation > Proceed to `Membership Type Assignment` (not yet implemented) so that Volunteer/Admin can select the desired type and log the payment (not yet implemented).

2 -  User creates an account on the website prior to the meeting. Same as above, but the workflow would stop after email confirmation as membership purchases should be done on-site.

**Comment by mark100net** [comment]
This has been implemented as far as a logged in user (admin or volunteer) being able to create a user.

It leaves the current user logged in, as you would expect.

Directing the volunteer/admin that signed them up to the agreements page so that user just created can do something with the agreements (even though the user that signed them up is still the one logged in) is probably not a practical implementation--but at least would require specification.

As to what should happen with the agreements in this context (or in any other contexts) should be part of the overall badly needed functionality review that I noted in another issue.
