### ISSUE TITLE
On User Page, Add "Effective Date" and "Expiration Date" input fields

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#256]
This task is dependent on #255 

Beneath the "Membership Type" dropdown being completed in #255 , add input fields for a date selection.

- The "Effective Date" should represent the date the Membership Type was changed/updated 
- The "Expiration Date" should be calculated based on the Membership Type's default length, from the "Effective Date"

![image](https://user-images.githubusercontent.com/47750744/72228840-3b921b00-3578-11ea-8101-ff3e90c10bd4.png)

**Comment by mark100net** [comment]
@abronkema This comment also applies to #257 

I would suggest having an `effective_date` and an `expiration_date` (rather than a `renewal status`). That way you don't have to rely on the status being manually toggled (or not) at the appropriate time.

I would also suggest we put all of this on a memberships table. Doing this now rather than later will avoid having to migrate when have more elaborate membership transaction support.

**Comment by pollygee** [comment]
@abronkema what do you think.  I think this will work.

**Comment by abronkema** [comment]
@mark100net @pollygee - I've updated this to reflect those ideas.

**Comment by pollygee** [comment]
@abronkema can we take off the blocked label or is this still blocked for some reason?

**Comment by mark100net** [comment]
This is part of memberships and is being handled elsewhere.
