### ISSUE TITLE
Update Nav Bar Alignment

### ISSUE THREAD

**Issue by abronkema** [rubyforgood/babywearing#81]
The nav bar currently shows icons and font that is not correctly aligned/sized. 

- Adjust sizing of the icons to be uniform
- Vertically center icons
- Adjust font size so that all text fits on a single line
- Align text along bottom of container
- Rename `INVENTORY` to `CARRIERS`

**Comment by Rgaliant** [comment]
Hello, I would love to give this a try. I should be able to make a PR by end of day or will comment again if I run into a block.

**Comment by pollygee** [comment]
@nisusam it looks like @Rgaliant grabbed this issue first.  Can you check out his changes and see if you saw anything he missed since you looked at this part of the code?  Next time, comment here when you start working on something so we can assign it to you and avoid doubling up!  There's plenty to go around, thanks for helping!
